name = "fakegps-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "."
binding = "ASSETS"
exclude = [".git", ".wrangler", "node_modules"]

routes = [
  { pattern = "www.sixzjd.sbs", custom_domain = true },
  { pattern = "sixzjd.sbs", custom_domain = true }
]
